### ISSUE TITLE
Postgresql to Mysql transfer problem

### ISSUE THREAD

**Issue by diegomguzman** [sqlpipe/sqlpipe#30]
When transferring tables from my PostgreSQL database into my MySQL database, I noticed that PostgreSQL Boolean columns were created as TEXT columns in the new MySQL database.  This caused my existing applications to crash. By making the new columns take TINYINT as data type any problems should be solved.

**Comment by calmitchell617** [comment]
Hi Diego, thanks for the bug report. This should be fixed by our upcoming release.CalOn Aug 26, 2023, at 6:24 PM, diegomguzman ***@***.***> wrote:﻿
When transferring tables from my PostgreSQL database into my MySQL database, I noticed that PostgreSQL Boolean columns were created as TEXT columns in the new MySQL database.  This caused my existing applications to crash. By making the new columns take TINYINT as data type any problems should be solved.

**Comment by calmitchell617** [comment]
Hi Diego,

Can you please try the latest version of SQLpipe (the project README should have all the info you need to get started) and see if this fixes the issue? It should be OK now.
